# This workflow will install Python dependencies and run all linting checks
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-prod.txt
        python -m pip install --editable .
        python -m pip install -r requirements-dev.txt
    - name: Check code formatting with ruff
      run: |
        ruff format jira_agile_metrics/ jira_agile_metrics/tests/ setup.py --check
    - name: Run ruff
      run: |
        ruff check jira_agile_metrics/ jira_agile_metrics/tests/ setup.py
    - name: Run pylint
      run: |
        pylint jira_agile_metrics/ jira_agile_metrics/tests/ setup.py
